[package]
name = "portascript"
version.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
rmx.workspace = true
uucore = "0.7.0"
uu_echo = "0.7.0"
uu_cat = "0.7.0"
uu_true = "0.7.0"
uu_false = "0.7.0"
uu_ls = "0.7.0"
uu_cp = "0.7.0"
uu_sort = "0.7.0"
uu_head = "0.7.0"
uu_tail = "0.7.0"
uu_mkdir = "0.7.0"
uu_rm = "0.7.0"
uu_mv = "0.7.0"
uu_chmod = "0.7.0"
uu_wc = "0.7.0"
uu_basename = "0.7.0"
uu_dirname = "0.7.0"
uu_touch = "0.7.0"
uu_tr = "0.7.0"
uu_cut = "0.7.0"
uu_tee = "0.7.0"
uu_uniq = "0.7.0"
uu_seq = "0.7.0"
uu_yes = "0.7.0"
uu_printf = "0.7.0"
os_pipe = "1"
indexmap = "2"
tempfile = "3"
gag = "1"
libc = "0.2"
